---
role:
  pkg:
    - git
  link:
    - ".gitconfig"
    - ".gitignore"
  template:
    - source: ".gitconfig.local.tpl"
      include_vars: ~/.gitconfig.local.yml
  vars:
    # git_author_name:
    # git_author_email:
    git_credential_helper: '{{if eq .OS "darwin"}}osxkeychain{{else}}{{.OS}}{{end}}'
    # git_signing_key:
    # git_commit_gpgsign:
  # line: # If not using GPG Suite:
  #   ".bash_profile": "export GPG_TTY=$(tty)"
  # post_install:
  #   - "if test ! -f ~/.gitconfig.local.yml; then cp .gitconfig.local.yml.example ~/.gitconfig.local.yml"; fi
