link:
  - ".gitconfig"
  - ".gitignore"
template: ".gitconfig.local.tpl"
env:
  # git_author_name:
  # git_author_email:
  credential_helper: '{{if eq "$OS" "darwin"}}osxkeychain{{else}}cache{{end}}'
